# Generated by Django 3.2.16 on 2023-06-16 19:56

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.png', upload_to=blog.models.upload_to, verbose_name='Image'),
        ),
    ]
